apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiaayou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiaayou
  template:
    metadata:
      labels:
        app: tiaayou
    spec:
      containers:
      - image: okteto.dev/tiaayou:latest
        name: tiaayou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4b75bb76-f04b-4231-b2de-567282dcd9ff"
        - name: Vless_Path
          value: "/vl46se5"
        - name: Vmess_UUID
          value: "4b75bb76-f04b-4231-b2de-567282dcd9ff"
        - name: Vmess_Path
          value: "/vm6hy86"
        - name: Share_Path
          value: "/v2link"
